### ISSUE TITLE
是不是transformers更新了？我跑得有错误

### ISSUE THREAD

**Issue by hulei0102** [Morizeyao/GPT2-Chinese#103]
Colaboratory上跑的，参数如下
!python /content/GPT2-Chinese/train.py \
  --model_config /content/GPT2-Chinese/config/model_config_small.json \
  --tokenized_data_path /content/tokenized/ \
  --tokenizer_path /content/GPT2-Chinese/cache/vocab_small.txt \
  --raw_data_path /content/GPT2-Chinese/train.json \
  --epochs 30 \
  --log_step 200 \
  --stride 512 \
  --output_dir model/ \
  --device 0,1,2,3 \
  --num_pieces 100 \
  --raw

直接跑提示错误：
  File "/content/GPT2-Chinese/train.py", line 143, in main
    scheduler = transformers.WarmupLinearSchedule(optimizer, warmup_steps=warmup_steps,
AttributeError: module 'transformers' has no attribute 'WarmupLinearSchedule'

尝试修改train.py
加了：from transformers import WarmupLinearSchedule ，提示transformers没有WarmupLinearSchedule了。没搞懂这个是干嘛的
    from transformers import WarmupLinearSchedule 
    optimizer = transformers.AdamW(model.parameters(), lr=lr, correct_bias=True)
    scheduler = WarmupLinearSchedule(optimizer, warmup_steps=warmup_steps,  t_total=total_steps)

**Comment by Morizeyao** [comment]
貌似是今天的更新导致的，pip install transformers==2.1.1 安装旧版本应该可以解决问题

**Comment by hulei0102** [comment]
!pip install transformers==2.1.1
的确，我更新了2.1.1能跑了。3Q
