### ISSUE TITLE
number of parameters: 81894144.RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by justin0314** [Morizeyao/GPT2-Chinese#104]
RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 2; 10.73 GiB total capacity; 9.59 GiB already allocated; 290.56 MiB free; 25.84 MiB cached)
我用16G内存的电脑为啥都跑不起来，我的train.json大概只有2MB左右.

**Comment by hulei0102** [comment]
batch_size设置大点吧，原配置太小

**Comment by walkingonthestreet** [comment]
(GPU 2; 10.73 GiB total capacity; 9.59 GiB already allocated; 290.56 MiB free; 25.84 MiB cached)
就是说你GPU ID 2的显卡 ，已经分配了9.59 GiB，还剩290.56 MiB ，已缓存25.84 MiB。
很显然， buy a higher performence graphics card to fix this error!

**Comment by HiIcy** [comment]
我有相同的问题，把batch_size 设为1 都不行,我不认为是显卡那里的问题, @walkingonthestreet

**Comment by walkingonthestreet** [comment]
@HiIcy 你是不是用jupyter跑，jupyter报错后要重启内核或者手动释放cuda内存，如果不是模型设置的太变态，除非你的显存还是古老的2G，否则不应该存在这种情况。

**Comment by lztz0022** [comment]
> 要重启内核或者手动释放cuda内存，如果不是模型设置的太变态，除非你的显存还是古老的2G，否则不应该存在这

在notebook里怎么手动释放cuda内存呢？

**Comment by zgd716** [comment]
> 我有相同的问题，把batch_size 设为1 都不行,我不认为是显卡那里的问题, @walkingonthestreet

大佬这个问题解决了吗?碰到一样的问题

**Comment by walkingonthestreet** [comment]
> > 要重启内核或者手动释放cuda内存，如果不是模型设置的太变态，除非你的显存还是古老的2G，否则不应该存在这
> 
> 在notebook里怎么手动释放cuda内存呢？

重启内核，或者使用pytorch的内存管理。

**Comment by jiandam55** [comment]
> (GPU 2; 10.73 GiB total capacity; 9.59 GiB already allocated; 290.56 MiB free; 25.84 MiB cached) 就是说你GPU ID 2的显卡 ，已经分配了9.59 GiB，还剩290.56 MiB ，已缓存25.84 MiB，却不自量力的尝试分配 384.00 MiB内存。 很显然... buy a higher performence graphics card or set lower parameters to fix this error,DGX-1 is good for you

(GPU 0; 15.75 GiB total capacity; 79.11 MiB already allocated; 3.62 MiB free; 86.00 MiB reserved in total by PyTorch)
我的问题更诡异，说有16G，才用了79M，为何就只剩下3.62M了？
