### ISSUE TITLE
No such file or directory: 'data/tokenized/tokenized_train_0.txt'

### ISSUE THREAD

**Issue by Youarerare** [Morizeyao/GPT2-Chinese#107]
报错信息  我直接运行python train.py:
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 138, in main
    with open(tokenized_data_path + 'tokenized_train_{}.txt'.format(i), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/tokenized/tokenized_train_0.txt'

我只有训练语料，想知道这个tokenized_train_0.txt该如何得到？

**Comment by dcpengjin** [comment]
我也遇到这个问题，请问除了train.json还需要别的文件吗？

**Comment by Youarerare** [comment]
不需要，这个应该是分词的问题。



---Original---

**Comment by micklexqg** [comment]
同样这个问题，你是怎么解决的

**Comment by Youarerare** [comment]
gpu模型需要一个词表，出现这个问题说明你没有生成词表，具体生成词表文件的方法这个项目主页上有



---Original---
