### ISSUE TITLE
关于生成速度

### ISSUE THREAD

**Issue by hzrpku** [Morizeyao/GPT2-Chinese#108]
生成的速度不够快，对于短文本。请问有什么办法吗？可以增加生成时的batchsize吗

**Comment by hzrpku** [comment]
代码已改好，生成时速度飞起～

**Comment by Morizeyao** [comment]
恭喜你，我最近不方便改代码～有心的话可以PR一下

**Comment by echoyes** [comment]
> 代码已改好，生成时速度飞起～

请问方便共享一下代码么？
