### ISSUE TITLE
损失下降到2左右，再也降不下去，是咋回事？

### ISSUE THREAD

**Issue by walkingonthestreet** [Morizeyao/GPT2-Chinese#109]
LR设置成0.0015了，16G数据喂了50个epoch，一直维持2.3左右无法下降。

**Comment by Morizeyao** [comment]
16G数据你能跑到50个epoch，机器很猛啊，2.3左右应该差不多了

**Comment by walkingonthestreet** [comment]
@Morizeyao 我是重写了一个DataLoader，原有的main里面数据加载耗时太大，GPU利用率太低，做好预缓存直接加载到GPU能满速运行，训练耗时能翻倍，我的机器只是1刀TITAN V而已。数据集嘛，自己写爬虫下载的，花了2天时间抓，54亿字，百万字数以上的小说，2581本。如果不限制字数的话，应该能有两三万本，没有几个DGX-1是跑不了了。model_config我修改了一下，没有要那么大，训练的时候步数跟步长调小了。

**Comment by Morizeyao** [comment]
没问题的，我因为特殊原因没有更新代码，最早的数据处理方式效率确实不高

**Comment by tianlongwang** [comment]
> @Morizeyao 我是重写了一个DataLoader，原有的main里面数据加载耗时太大，GPU利用率太低，做好预缓存直接加载到GPU能满速运行，训练耗时能翻倍，我的机器只是1刀TITAN V而已。数据集嘛，自己写爬虫下载的，花了2天时间抓，54亿字，百万字数以上的小说，2581本。如果不限制字数的话，应该能有两三万本，没有几个DGX-1是跑不了了。model_config我修改了一下，没有要那么大，训练的时候步数跟步长调小了。

你重写的data loader能分享一下吗？我也发现gpu跑不满，很不爽。

**Comment by tianlongwang** [comment]
> @Morizeyao 我是重写了一个DataLoader，原有的main里面数据加载耗时太大，GPU利用率太低，做好预缓存直接加载到GPU能满速运行，训练耗时能翻倍，我的机器只是1刀TITAN V而已。数据集嘛，自己写爬虫下载的，花了2天时间抓，54亿字，百万字数以上的小说，2581本。如果不限制字数的话，应该能有两三万本，没有几个DGX-1是跑不了了。model_config我修改了一下，没有要那么大，训练的时候步数跟步长调小了。



> @Morizeyao 我是重写了一个DataLoader，原有的main里面数据加载耗时太大，GPU利用率太低，做好预缓存直接加载到GPU能满速运行，训练耗时能翻倍，我的机器只是1刀TITAN V而已。数据集嘛，自己写爬虫下载的，花了2天时间抓，54亿字，百万字数以上的小说，2581本。如果不限制字数的话，应该能有两三万本，没有几个DGX-1是跑不了了。model_config我修改了一下，没有要那么大，训练的时候步数跟步长调小了。

另外，你的爬虫从哪个网站抓的小说？还有你1刀买了个TitanV？NB！

**Comment by walkingonthestreet** [comment]
> > @Morizeyao 我是重写了一个DataLoader，原有的main里面数据加载耗时太大，GPU利用率太低，做好预缓存直接加载到GPU能满速运行，训练耗时能翻倍，我的机器只是1刀TITAN V而已。数据集嘛，自己写爬虫下载的，花了2天时间抓，54亿字，百万字数以上的小说，2581本。如果不限制字数的话，应该能有两三万本，没有几个DGX-1是跑不了了。model_config我修改了一下，没有要那么大，训练的时候步数跟步长调小了。
> 
> > @Morizeyao 我是重写了一个DataLoader，原有的main里面数据加载耗时太大，GPU利用率太低，做好预缓存直接加载到GPU能满速运行，训练耗时能翻倍，我的机器只是1刀TITAN V而已。数据集嘛，自己写爬虫下载的，花了2天时间抓，54亿字，百万字数以上的小说，2581本。如果不限制字数的话，应该能有两三万本，没有几个DGX-1是跑不了了。model_config我修改了一下，没有要那么大，训练的时候步数跟步长调小了。
> 
> 另外，你的爬虫从哪个网站抓的小说？还有你1刀买了个TitanV？NB！

cishuge,一个单核512M内存的垃圾站群。1刀TITAN V ，是一块的意思，不是dollar。
