### ISSUE TITLE
请问是从预训练模型开始训练的吗？

### ISSUE THREAD

**Issue by Dongfeng-He** [Morizeyao/GPT2-Chinese#11]
非常感谢能分享这么好的项目。有几个问题想请教一下。
请问一开始模型参数是加载的预训练模型，还是只是简单的初始化？
如果是从预训练模型开始训练，是使用OpenAI开源的预训练模型吗？
如果是从头开始训练，只用几百M的语料就已经足够了吗，毕竟OpenAI用了40G的语料。从头开始训练在四卡2080Ti上大概需要多长时间呢？

**Comment by Morizeyao** [comment]
GPT2中文没有预训练模型，项目内的三个例子都是从零开始训练的。从头开始练的话，要取得比较乐观的效果需要的时间主要取决于语料量。300MB语料的话练一天可以。如果有进一步问题欢迎加qq交流，330501241。

**Comment by Dongfeng-He** [comment]
感谢感谢，QQ加你了，希望能交流一下！
