### ISSUE TITLE
AttributeError: module 'transformers' has no attribute 'WarmupLinearSchedule'

### ISSUE THREAD

**Issue by valexsyu** [Morizeyao/GPT2-Chinese#111]
當在跑 train.py時, 會出現底下的error.  請問是什麼問題呢?謝謝

using device: cuda
number of parameters: 81894144
calculating total steps
100%|████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [06:06<00:00,  3.67s/it]
total steps = 2221865
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 144, in main
    scheduler = transformers.WarmupLinearSchedule(optimizer, warmup_steps=warmup_steps,
AttributeError: module 'transformers' has no attribute 'WarmupLinearSchedule'

**Comment by Morizeyao** [comment]
请安装transformers==2.1.1版本

**Comment by valexsyu** [comment]
好的,謝謝回覆.
