### ISSUE TITLE
prefix无法写入中文

### ISSUE THREAD

**Issue by Superice666** [Morizeyao/GPT2-Chinese#113]
如题，我想通过另一个python脚本调用，但发现无法在prefix中写入中文。
os.system(u'python3 /usr/lib/cgi-bin/generator/GPT2-Chinese-master/generate.py   --device=0   --length=300   --nsamples=1 --prefix="中文"   --tokenizer_path=/usr/lib/cgi-bin/generator/GPT2-Chinese-master/cache/vocab_small.txt   --model_path=/usr/lib/cgi-bin/generator/GPT2-Chinese-master/model/final_model   --topp=1   --fast_pattern   --save_samples   --temperature=1.0')

To use data.metrics please install scikit-learn. See https://scikit-learn.org/stable/index.html: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.854066 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215: \r  0%|          | 0/300 [00:00<?, ?it/s]: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.857177 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215: \r  0%|          | 0/300 [00:00<?, ?it/s]: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.857316 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215: : /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.896860 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215: Traceback (most recent call last):: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.896937 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/lib/cgi-bin/generator/GPT2-Chinese-master/generate.py", line 226, in <module>: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.896947 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     main(): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.896993 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/lib/cgi-bin/generator/GPT2-Chinese-master/generate.py", line 191, in main: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897046 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     temperature=temperature, top_k=topk, top_p=topp, repitition_penalty=repetition_penalty, device=device: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897092 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/lib/cgi-bin/generator/GPT2-Chinese-master/generate.py", line 119, in generate: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897105 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     device=device): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897156 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/lib/cgi-bin/generator/GPT2-Chinese-master/generate.py", line 104, in fast_sample_sequence: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897176 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     output = model(prev, past=past): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897230 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897254 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     result = self.forward(*input, **kwargs): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897304 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_gpt2.py", line 533, in forward: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897331 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     head_mask=head_mask): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897380 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 541, in __call__: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897403 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     result = self.forward(*input, **kwargs): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897452 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:   File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_gpt2.py", line 373, in forward: /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897479 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215:     input_ids = input_ids.view(-1, input_shape[-1]): /usr/lib/cgi-bin/gpt2.py
[Sat Dec 07 20:42:24.897550 2019] [cgi:error] [pid 1021:tid 140441722771200] [client 123.234.234.72:59092] AH01215: RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0] because the unspecified dimension size -1 can be any value and is ambiguous: /usr/lib/cgi-bin/gpt2.py

**Comment by Morizeyao** [comment]
如果直接调用的话应该是可以的吧？可能和间接调用有关？

**Comment by WenbinTan** [comment]
我也遇到了同样的问题， @Superice666 ，请问你解决了吗？

**Comment by asd51731** [comment]
> 我也遇到了同样的问题， @Superice666 ，请问你解决了吗？

直接调用就可以，按照readme里面我这几天刚跑了，是可以的
