### ISSUE TITLE
请教只训练语言模型

### ISSUE THREAD

**Issue by kangkang61** [Morizeyao/GPT2-Chinese#12]
您好，我想请问一下我只想要从头训练一个语言模型来计算句子的ppl，应该如何使用您的代码呢，是不是只要使用train.py和预处理的代码呢，generate.py是不是用不上呢，谢谢您~

**Comment by Morizeyao** [comment]
只需使用train.py即可，generate.py用不上的。有进一步问题可以加qq330501241交流
