### ISSUE TITLE
GPU memory用掉了，但是utilization一直在2%左右，怎么办？

### ISSUE THREAD

**Issue by tianlongwang** [Morizeyao/GPT2-Chinese#126]
网上查跟data_loader和num_workers有关，找不到相关的code，求问怎么把gpu跑满？

**Comment by liuzhejun** [comment]
单进程的DataParallel是不可能把GPU跑满的，可以使用多进程分布式训练，速度可以翻几倍，详情见：https://pytorch.org/tutorials/intermediate/ddp_tutorial.html

**Comment by Morizeyao** [comment]
是的没错
