### ISSUE TITLE
使用Huggingface Transformers读入模型报错

### ISSUE THREAD

**Issue by ZeweiChu** [Morizeyao/GPT2-Chinese#137]
可能由于最近Huggingface Transformers更新较多，读入模型报以下错误：

> 
> 03/25/2020 13:19:54 - INFO - transformers.configuration_utils -   loading configuration file ../ProseInChinese/config.json
> Traceback (most recent call last):
>   File "run_language_modeling.py", line 766, in <module>
>     main()
>   File "run_language_modeling.py", line 663, in main
>     config = AutoConfig.from_pretrained(args.model_name_or_path, cache_dir=args.cache_dir)
>   File "/share/data/lang/users/zeweichu/software/anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/configuration_auto.py", line 198, in from_pretrained
>     "in its name: {}".format(pretrained_model_name_or_path, ", ".join(CONFIG_MAPPING.keys()))
> ValueError: Unrecognized model in ../ProseInChinese/. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: t5, distilbert, albert, camembert, xlm-roberta, bart, roberta, flaubert, bert, openai-gpt, gpt2, transfo-xl, xlnet, xlm, ctrl

我在config.json中加入 "model_type": "gpt2"之后报以下错误：

> Traceback (most recent call last):
>   File "run_language_modeling.py", line 766, in <module>
>     main()
>   File "run_language_modeling.py", line 675, in main
>     tokenizer = AutoTokenizer.from_pretrained(args.model_name_or_path, cache_dir=args.cache_dir)
>   File "/share/data/lang/users/zeweichu/software/anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/tokenization_auto.py", line 192, in from_pretrained
>     return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>   File "/share/data/lang/users/zeweichu/software/anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 393, in from_pretrained
>     return cls._from_pretrained(*inputs, **kwargs)
>   File "/share/data/lang/users/zeweichu/software/anaconda3/envs/transformers/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 496, in _from_pretrained
>     list(cls.vocab_files_names.values()),
> OSError: Model name '../ProseInChinese/' was not found in tokenizers model name list (gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2). We assumed '../ProseInChinese/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

有人知道怎么改预训练模型适应新的setting吗？

**Comment by Morizeyao** [comment]
请按照requirements.txt内说明使用transformers 2.1.1试试看，如果有问题的话我来修正
