### ISSUE TITLE
短文本（几句话）怎么做到训练和生成不换行？

### ISSUE THREAD

**Issue by kawa23** [Morizeyao/GPT2-Chinese#143]
@Morizeyao  你好，感谢你的工作。我在训练短文本（几句话）后生成时句子，会出现换行（长文本中因为段落需要）现象，但是短文本不需要，因为换行后，生成时句子换行前后的句子间不够连贯，虽然换行前后的每句话很通顺。如何做到训练和生成时都不换行呢？

**Comment by zhaokanghuiasd** [comment]
您好，我想问一下您的这个问题是如何解决的呢？
