### ISSUE TITLE
Tokenizer的区别

### ISSUE THREAD

**Issue by Charon922** [Morizeyao/GPT2-Chinese#149]
你好,

我想问Bert Tokenizer，分词版Bert Tokenizer以及BPE Tokenizer 这个三个的使用分别有什么区别和影响.

我想问为什么不直接用gtp2的tokenizer?

谢谢

**Comment by tomguluson92** [comment]
同问～

**Comment by Morizeyao** [comment]
都可以用的，稍微改一下代码就行，使用的区别需要实践体会哈
