### ISSUE TITLE
训练的loss或者ppl？使用分字和分词的效果对比？

### ISSUE THREAD

**Issue by fengzuo97** [Morizeyao/GPT2-Chinese#15]
作者能够提供一下在新闻预料上训练时最后的loss或者ppl？我试验过使用bert的tokenizer，也就是用字作为基本单位，loss下降的情况并没有subword好，文本生成的效果没有比较，不知道作者有没有进行过这方面的比较？

**Comment by Morizeyao** [comment]
loss训练到1以内会得到较可读效果。以我的实验经验，越大的语料越难得到低loss，因此loss仅作参考，还是得以实际生成效果为准。
本项目使用了Bert的tokenizer，没有与别的分词方式进行比较。Subword是指哪种方式？

**Comment by fengzuo97** [comment]
gpt2作者提到的是用byte level的bpe，所以我推测中文也应该用bpe，我具体使用的是sentencepiece工具。

**Comment by Morizeyao** [comment]
嗯，用sentencepiece是可行的，有实验结果的话欢迎分享。

**Comment by fengzuo97** [comment]
您在代码中分别构建了普通的tokenizer和tokenizer without wordpiece，不知道有没有比较这两种tokenizer对训练的影响呢？

**Comment by Morizeyao** [comment]
暂时只有普通tokenizer生成的效果。without wordpiece的版本还没有做实验，只写出了代码。
不做wordpiece，可以提高tokenize速度，减少vocab大小，我接下来会实验效果如何。

**Comment by fengzuo97** [comment]
ok，谢谢作者，个人实验不同的tokenizer方式，包括使用不同的语料得到的vocab都会对训练产生较大的影响，所以对这一块比较感兴趣，期待作者的跟进。如果得到了有意义的对比结果，我也会分享出来。

**Comment by Morizeyao** [comment]
是的，有个朋友也在用他的设备和我的代码实验分词之后训练的效果，你要是有兴趣交流的话可以加qq 330501241进一步联系

**Comment by Morizeyao** [comment]
我已经添加了分词模式，可以试验了。
