### ISSUE TITLE
项目包安装完成后,按照使用方法里的提示,运行报错,

### ISSUE THREAD

**Issue by qiubiteme** [Morizeyao/GPT2-Chinese#151]
我是个新手.跑的斗破的语料,语料直接跑会出问题,然后写了个脚本处理文本为json格式还是不行,现在不知道怎么弄了

(venv) qiuyang@qiuyang:~/project_list/GPT2-Chinese$ python train.py  --raw
args:
Namespace(batch_size=8, bpe_token=False, device='0,1,2,3', encoder_json='tokenizations/encoder.json', epochs=5, fp16=False, fp16_opt_level='O1', gradient_accumulation=1, log_step=1, lr=0.00015, max_grad_norm=1.0, min_length=128, model_config='config/model_config_small.json', num_pieces=100, output_dir='model/', pretrained_model='', raw=True, raw_data_path='data/train.txt', segment=False, stride=768, tokenized_data_path='data/tokenized/', tokenizer_path='cache/vocab_small.txt', vocab_bpe='tokenizations/vocab.bpe', warmup_steps=2000, writer_dir='tensorboard_summary/')
config:
{
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "finetuning_task": null,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 10,
  "n_positions": 1024,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torchscript": false,
  "use_bfloat16": false,
  "vocab_size": 13317
}

using device: cpu
building files
reading lines
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 118, in main
    full_tokenizer=full_tokenizer, min_length=min_length)
  File "train.py", line 18, in build_files
    lines = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by VYXUOF** [comment]
我也同样遇到过这个问题  这个是可以直接用txt跑的  把读取lines = json.load(f)改成lines = f.readlines()就ok了

**Comment by Morizeyao** [comment]
ok

**Comment by PaulCnth** [comment]
> 我也同样遇到过这个问题 这个是可以直接用txt跑的 把读取lines = json.load(f)改成lines = f.readlines()就ok了

亲测可用。
