### ISSUE TITLE
Bug in generate.py

### ISSUE THREAD

**Issue by gongel** [Morizeyao/GPT2-Chinese#155]
https://github.com/Morizeyao/GPT2-Chinese/blob/825f9b0d94916f6af0366fe2617b1bf5f065833c/generate.py#L182-L192

上面的out返回的是一条生成语句，并不是一个batch，所以下面L190的循环没意义。batch size=4，同一个结果打印了四次。

**Comment by Morizeyao** [comment]
感谢分享！你说的没错
