### ISSUE TITLE
看了gpt3，过来的

### ISSUE THREAD

**Issue by luyifanlu** [Morizeyao/GPT2-Chinese#158]
看到gpt3，发现nlp已经如此强大了。1700亿参量，也只有openai这样的企业才做的了，而且开源了。在中国本土，可能很难出现这样model，毕竟这种公益性质，花费大，和自己公司无关的研究。在中国没太有人做

**Comment by yhcRid** [comment]
兄弟请问你说的gpt3在哪里看呀？

**Comment by yhcRid** [comment]
> 看到gpt3，发现nlp已经如此强大了。1700亿参量，也只有openai这样的企业才做的了，而且开源了。在中国本土，可能很难出现这样model，毕竟这种公益性质，花费大，和自己公司无关的研究。在中国没太有人做

兄弟请问你说的gpt3在哪里看呀？

**Comment by luyifanlu** [comment]
英文版的 ，openai不是开源了吗

**Comment by luyifanlu** [comment]
直接github gpt3就看的到

**Comment by walkingonthestreet** [comment]
gpt-3不是凡人所能企及的

**Comment by allenxcp** [comment]
智源公开了 中文的 GPT-3模型，模型文件太大了5.4G
