### ISSUE TITLE
求教一般训练几个epoch？

### ISSUE THREAD

**Issue by ZhaoyueSun** [Morizeyao/GPT2-Chinese#16]
需要训练多少epoch是否有个经验值？是否和数据量有关，有没有什么参考意见？

**Comment by Morizeyao** [comment]
从经验上看，数据量越大需要训练的epoch越少。
数据如果比较小的话，可以训练数十个epoch。
因为代码里包含了每个epoch保存模型的功能，所以可以对于每个节点分别进行生成，观察并比较生成的效果。
如有1G以上的数据，训练一个epoch其实就可以观察到比较可观的生成效果了。当然，对大数据来说，训练的越久越好。

**Comment by ZhaoyueSun** [comment]
非常感谢！

**Comment by fengzuo97** [comment]
试验5个epoch基本可以收敛，英伟达训练megatron gpt2也是5个epoch收敛
