### ISSUE TITLE
大佬们 安装依赖就只要运行pip install -r requirements.txt 就可以了吗？ 

### ISSUE THREAD

**Issue by drizzt00s** [Morizeyao/GPT2-Chinese#162]
大佬们 安装依赖就只要运行pip install -r requirements.txt 就可以了吗？  很多报错，本来装了py3.6.1 和 tensorflow 1.3

**Comment by liaoxuewei** [comment]
不行啊，开始安装不到torch依赖包，后来通过下载包本地安装可以了，但是运行又出现：
E:\Opensource\GPT2-Chinese>generate.py
Traceback (most recent call last):
  File "E:\Opensource\GPT2-Chinese\generate.py", line 1, in <module>
    import torch
  File "E:\Python37\lib\site-packages\torch\__init__.py", line 102, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的模組。
网上各种说法都试过，还是不行，有点纳闷，python37，是我py版本太高了吗？

**Comment by liaoxuewei** [comment]
继续查找原因发现：
我电脑没有独立显卡，到pytorch的官网下载了一个cpu版本的pytorch就可以启动了，不完全确定是不是这个问题导致的！！！但是碰到这个问题的人可以尝试。

**Comment by Morizeyao** [comment]
感谢分享！

**Comment by BiEchi** [comment]
我用的学校服务器,架构是PowerPC,啥都要从头自己装,难顶..
