### ISSUE TITLE
#局部收敛问题

### ISSUE THREAD

**Issue by cyl250** [Morizeyao/GPT2-Chinese#17]
您好，请问您在训练过程中有碰到训练到一定时候loss开始抖动嘛，训练了大概1000多步开始？

**Comment by Morizeyao** [comment]
貌似没有遇到过类似情况，你的语料是不是有点少？学习率和batch size分别是多少？抖动时loss大约是多少？具体情况可以加qq讨论一下

**Comment by cyl250** [comment]
语料：大概2个g，学习率：您代码中的还试了一个0.000001，batch_size:默认，抖动loss跑了几次大概在4左右，5左右，6左右都有过，stride=2，n_ctx=35

**Comment by Morizeyao** [comment]
因为你的nctx比较小，所以选用大一些的batch size可能会好点。学习率的话1e-4左右即可。
语料的话你用的可能有点多，可以先用小语料测试，一般几十MB的特定领域语料就可以训练出不错的生成效果了。如果收敛情况稳定的话再测试大语料的情况。

**Comment by cyl250** [comment]
好的，谢谢您，我已经在尝试改了，还有一个问题哈，现在我把n_ctx=40,在处理数据时在bulid_file那边会出现一个错误。
“Token indixes sequence length is longer than the specified maximun sequence length for this model(42>40) Running this sequence through the model will result in indexing errors ”但是这个erro并不影响后面的训练不会报错，我的理解是在bulid_file时只是把文件分为了小分，为什么会出现这个erro呢，这个会不会影响之后的训练呢

**Comment by Morizeyao** [comment]
这个错误可以无视，提示来自于Pytorch-Transformers所以我就没去改动，对本项目没有影响。
但是从你这个报错看，你的num_pieces可能分的有点多了，当然也不好说，你可以关注一下。

**Comment by cyl250** [comment]
好的，谢谢您，万分感谢~
