### ISSUE TITLE
安装问题：CUDA10.0不支持pytorch1.4版本怎么办

### ISSUE THREAD

**Issue by chenruhai** [Morizeyao/GPT2-Chinese#187]
安装问题：CUDA10.0不支持pytorch1.4版本怎么办？(能不能不改变CUDA版本的情况下安装pytorch1.4版本呢)
官网的版本匹配：https://pytorch.org/get-started/previous-versions/

**Comment by JHR0717** [comment]
conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=9.2 -c pytorch
可以用cuda9.2
