### ISSUE TITLE
#loss每个num_piece会先增加再减

### ISSUE THREAD

**Issue by cyl250** [Morizeyao/GPT2-Chinese#19]
您好，loss在每读一个新的num_piece之后loss会增加再往下降低，这是正常的嘛，比如从2.多突然增到5.多，再继续往下降低，这是为什么呢？

**Comment by Morizeyao** [comment]
奇怪，我没遇到这个情况。。

**Comment by Morizeyao** [comment]
貌似这个问题在增加样本数量之后会消失？

**Comment by LeeCP8** [comment]
![loss](https://user-images.githubusercontent.com/17487200/64222264-0e669980-cf02-11e9-97c3-5293f25b0d96.png)
我也是这个情况，每一个num_piece迭代，就先升后降，到后面更是明显，我来增加数量试试

**Comment by Morizeyao** [comment]
怪了
