### ISSUE TITLE
"generate.py" 报错 "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte"

### ISSUE THREAD

**Issue by bestcccc1232123** [Morizeyao/GPT2-Chinese#192]
当我使用以下命令
```
./generate.py --length=50 --nsamples=4 --fast_pattern --model_config=models/poet_chn/config.json --tokenizer_path=models/poet_chn/vocab.txt --model_path=models/poet_chn/pytorch_model.bin
```
命令总是报错
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

我使用的是Ubuntu 20.04. 我下载了中文诗词model， 三个文件放在`./models/poet_chn`下面。

**Comment by changzhiluo** [comment]
兄弟，估计你路径搞错了。比如我下载了古诗的模型，里面有“config.json”， “pytorch_model.bin”和“vocab.txt”三个东西，我放到了"./model/gushi"目录下。生成古诗方法如下：

python generate.py \
  --device 0 \
  --length 50 \
  --tokenizer_path model/gushi/vocab.txt \
  --model_path model/gushi \
  --prefix "[CLS]过往皆烟云，" \
  --topp 1 \
  --temperature 1.0

**Comment by libralibra** [comment]
model path是文件夹，不是model文件名，指定参数时改成/models/poet_chn就可以了
