### ISSUE TITLE
同样的代码，在win笔记本可以train，在linux台式机下显示killed

### ISSUE THREAD

**Issue by libralibra** [Morizeyao/GPT2-Chinese#195]
代码完全一样，复制到google colab运行一会儿之后，不显示loss，然后出现一个^C就结束了。
我就把代码复制到linux台式机上去跑，结果能看到2行step和loss，然后就直接显示Killed，可能是什么原因？

![tttttttttttttttt](https://user-images.githubusercontent.com/875627/109435766-006cd880-7a14-11eb-94cd-bde316e81f41.PNG)

**Comment by JHR0717** [comment]
可能是内存不够了
