### ISSUE TITLE
软件包安装问题

### ISSUE THREAD

**Issue by chiangandy** [Morizeyao/GPT2-Chinese#20]
我用sudo pip3 install -r requirements.txt 安装package.
安装显示正常...
但import tokenization_bert 会找不到package....
请问这会是哪出错了？

(pytorch_p36) ubuntu@ip-172-31-38-29:~$ sudo pip3 install -r requirements.txt
Requirement already satisfied: pytorch-transformers in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 1)) (1.0.0)
Requirement already satisfied: pytorch-pretrained-bert in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2)) (0.6.2)
Requirement already satisfied: torch in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4)) (1.17.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5)) (4.33.0)
Requirement already satisfied: sklearn in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6)) (0.0)
Requirement already satisfied: keras in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 7)) (2.2.4)
Requirement already satisfied: tb-nightly in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 8)) (1.15.0a20190813)
Requirement already satisfied: boto3 in /usr/local/lib/python3.5/dist-packages (from pytorch-transformers->-r requirements.txt (line 1)) (1.9.72)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.5/dist-packages (from pytorch-transformers->-r requirements.txt (line 1)) (0.1.82)
Requirement already satisfied: regex in /usr/local/lib/python3.5/dist-packages (from pytorch-transformers->-r requirements.txt (line 1)) (2019.6.8)
Requirement already satisfied: requests in /usr/local/lib/python3.5/dist-packages (from pytorch-transformers->-r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.5/dist-packages (from sklearn->-r requirements.txt (line 6)) (0.20.2)
Requirement already satisfied: scipy>=0.14 in /usr/lib/python3/dist-packages (from keras->-r requirements.txt (line 7)) (0.17.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from keras->-r requirements.txt (line 7)) (3.11)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.5/dist-packages (from keras->-r requirements.txt (line 7)) (1.12.0)
Requirement already satisfied: keras-applications>=1.0.6 in /usr/local/lib/python3.5/dist-packages (from keras->-r requirements.txt (line 7)) (1.0.8)
Requirement already satisfied: keras-preprocessing>=1.0.5 in /usr/local/lib/python3.5/dist-packages (from keras->-r requirements.txt (line 7)) (1.1.0)
Requirement already satisfied: h5py in /usr/lib/python3/dist-packages (from keras->-r requirements.txt (line 7)) (2.6.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (0.15.5)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (0.7.1)
Requirement already satisfied: protobuf>=3.6.0 in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (3.9.0)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (0.33.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (3.1.1)
Requirement already satisfied: grpcio>=1.6.3 in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (1.22.0)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.5/dist-packages (from tb-nightly->-r requirements.txt (line 8)) (41.0.1)
Requirement already satisfied: botocore<1.13.0,>=1.12.72 in /usr/local/lib/python3.5/dist-packages (from boto3->pytorch-transformers->-r requirements.txt (line 1)) (1.12.206)
Requirement already satisfied: s3transfer<0.2.0,>=0.1.10 in /usr/local/lib/python3.5/dist-packages (from boto3->pytorch-transformers->-r requirements.txt (line 1)) (0.1.13)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.5/dist-packages (from boto3->pytorch-transformers->-r requirements.txt (line 1)) (0.9.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->pytorch-transformers->-r requirements.txt (line 1)) (2019.6.16)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->pytorch-transformers->-r requirements.txt (line 1)) (1.25.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->pytorch-transformers->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->pytorch-transformers->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: docutils<0.15,>=0.10 in /usr/lib/python3/dist-packages (from botocore<1.13.0,>=1.12.72->boto3->pytorch-transformers->-r requirements.txt (line 1)) (0.12)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /usr/local/lib/python3.5/dist-packages (from botocore<1.13.0,>=1.12.72->boto3->pytorch-transformers->-r requirements.txt (line 1)) (2.8.0)
(pytorch_p36) ubuntu@ip-172-31-38-29:~$ python3
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytorch_transformers
>>> import torch
>>> import tokenization_bert
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tokenization_bert'
>>>

**Comment by Morizeyao** [comment]
tokenization_bert不是module，是项目内的一个文件，这里import是import这个文件而不是import包。你看看问题是不是出在这？

**Comment by chiangandy** [comment]
感谢～是我安装包上传没完整，已修正～感谢
