### ISSUE TITLE
训练语料处理问题

### ISSUE THREAD

**Issue by BruceHan98** [Morizeyao/GPT2-Chinese#202]
我按照["第一篇文章的正文", "第二篇文章的正文", "第三篇文章的正文"]的格式，将15部金庸小说放入一个train.json文件中，在训练时一直卡在reading lines部分，token文件都为0B，参数如下：

config:
{
  "attn_pdrop": 0.1,
  "embd_pdrop": 0.1,
  "finetuning_task": null,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 1024,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pruned_heads": {},
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "torchscript": false,
  "use_bfloat16": false,
  "vocab_size": 21128
}

using device: cuda
building files
reading lines
  0%|                                                                                                                                     | 0/256 [00:00<?, ?it/s]

**机器是Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz，15 GB + GeForce RTX 2080 Ti 11GB。**

请问是什么问题？

**Comment by BruceHan98** [comment]
嗯，是时间问题，加载需要漫长的等待......

**Comment by BiEchi** [comment]
`i3`是真的牛
