### ISSUE TITLE
训练数据train.json格式是什么样的，教程中说每行一个json字符串，没明白什么意思，能上传一下训练数据的examples吗

### ISSUE THREAD

**Issue by DequanZhu** [Morizeyao/GPT2-Chinese#209]

**Comment by JHR0717** [comment]
一行一个字符串也行

“line1line1line1line1line1”
“line2line2line2line2line2”
“line3line3line3line3line3”
……
注意 1.每行都需要两边加双引号 2.不要有回车空行
