### ISSUE TITLE
OOM内存问题

### ISSUE THREAD

**Issue by idiomer** [Morizeyao/GPT2-Chinese#215]
RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 14.76 GiB total capacity; 11.04 GiB already allocated; 259.75 MiB free; 11.10 GiB reserved in total by PyTorch)

很明显内存不足报错了，请问训练模型最少需要多少内存

**Comment by jiandam55** [comment]
(GPU 0; 15.75 GiB total capacity; 79.11 MiB already allocated; 3.62 MiB free; 86.00 MiB reserved in total by PyTorch)
我的问题更诡异，说有16G，才用了79M，为何就只剩下3.62M了？
