### ISSUE TITLE
#分词训练格式

### ISSUE THREAD

**Issue by kangkang61** [Morizeyao/GPT2-Chinese#23]
您好，想请问一下我如果想以词级别来训练语言模型，是需要用tokenization_bert_without_wordpiece.py这个数据预处理嘛，文本的格式是需要分好词的格式吗，比如“今天  天气  真好”

**Comment by Morizeyao** [comment]
不是。
分词生成的话需要重写tokenizer了

**Comment by Morizeyao** [comment]
我已经添加了分词模式，可以试用了。

**Comment by kangkang61** [comment]
好的，感谢！采用分词的话输入的原始语料是已经分好词的语料比如‘今天 天气 很好’嘛？

**Comment by Morizeyao** [comment]
不用事先分词，我写的tokenizer会调用thulac帮你分
