### ISSUE TITLE
加载模型配置的时候也是从pytorch_model_bin加载吗，但他不是个json文件

### ISSUE THREAD

**Issue by nus07** [Morizeyao/GPT2-Chinese#242]
![QQ截图20220302091952](https://user-images.githubusercontent.com/89561322/156276496-cef7fcc5-fe93-4641-bccb-a01f0fd50067.png)
![QQ截图20220302092148](https://user-images.githubusercontent.com/89561322/156276650-00b175db-9df1-402f-b5af-976999611917.png)

**Comment by disanda** [comment]
这个问题怎么解决呢？
