### ISSUE TITLE
cannot import name 'clean_up_tokenization'

### ISSUE THREAD

**Issue by leemengtaiwan** [Morizeyao/GPT2-Chinese#25]
嗨，我使用 `pip install -r requirements.txt` 設定好環境，但是跑 `train_single.py` 時出現底下 import 錯誤，有人碰到一樣情況嗎？

```
Traceback (most recent call last):
  File "train_single.py", line 223, in <module>
    main()
  File "train_single.py", line 65, in main
    from tokenizations import tokenization_bert_without_wordpiece as tokenization_bert
  File "/content/GPT2-Chinese/tokenizations/tokenization_bert_without_wordpiece.py", line 25, in <module>
    from pytorch_transformers.tokenization_utils import PreTrainedTokenizer, clean_up_tokenization
ImportError: cannot import name 'clean_up_tokenization'
```
看[官方實現](https://github.com/huggingface/pytorch-transformers/blob/88efc65bac63bdc6b4123eb225235538a7096034/pytorch_transformers/tokenization_utils.py#L649)有定義 `clean_up_tokenization`，不過一時想不到怎麼解決這個 import error.

**Comment by wanpower** [comment]
我直接删除掉之后可以训练，你可以试试，怀疑是因为pytorch_transformers.tokenization_utils的版本更新造成的，在我下载的版本里，clean_up_tokenization是一个方法，而只有类才可以import

**Comment by Morizeyao** [comment]
你们俩都遇到这个问题了吗？那可能确实是pytorch transformers更新导致的，我来想想办法

**Comment by wanpower** [comment]
> 你们俩都遇到这个问题了吗？那可能确实是pytorch transformers更新导致的，我来想想办法

是的，我也遇到了

**Comment by Morizeyao** [comment]
可以先退回1.0版本的pytorch transformers。我到家之后来修bug

**Comment by Morizeyao** [comment]
直接删掉就行了，我已经更新了代码。

**Comment by leemengtaiwan** [comment]
@Morizeyao error 消失了，十分感謝！
