### ISSUE TITLE
是否保存optimizer的参数？

### ISSUE THREAD

**Issue by fengzuo97** [Morizeyao/GPT2-Chinese#26]
作者在保存模型时没有保存optimizer的参数和scheduler的参数，是否会对中断后继续训练有影响？

**Comment by Morizeyao** [comment]
有影响的，中断后继续训练，不保存optimizer和scheduler的话无法恢复学习率参数。
目前只做了基于预训练模型继续训练的代码，没有做中断恢复训练的代码。
