### ISSUE TITLE
为何生成文章的速度极慢

### ISSUE THREAD

**Issue by jiandam55** [Morizeyao/GPT2-Chinese#267]
作者大侠你好，为何生成文章的速度极慢，只有3秒一个字，请指导原因及如何改进
我的生成语句是：
python ./generate.py --length=2000 --nsamples=4 --prefix=进一步加强和改进机关作风建设的实施意见 --save_samples --save_samples_path=/mnt/20230208163910

**Comment by jiandam55** [comment]
是否搞个好点的电脑，使用GPU就可以解决？

**Comment by Minjuner-97** [comment]
你的length有点大了， 不过我的只有250的时候，也很慢，跑在服务器虚拟机上，比我本机还慢。。

**Comment by jiandam55** [comment]
感谢回复，您说的原因也有，不过后面我还发现了一个另外的原因：我本地没装独立显卡，所以GPU没用上，呵呵




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Morizeyao/GPT2-Chinese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Morizeyao/GPT2-Chinese] 为何生成文章的速度极慢 (Issue #267)





 
你的length有点大了， 不过我的只有250的时候，也很慢，跑在服务器虚拟机上，比我本机还慢。。
