### ISSUE TITLE
请问能否支持非续写模式的generate?

### ISSUE THREAD

**Issue by lexmen318** [Morizeyao/GPT2-Chinese#29]
你好！

当前的generator应该属于命题作文类，或者“续写”模式。

我的需求是这样的：给定一句话，生成另外一句话（限定最大长度）。

进而我想实现的需求是生成的这句话与给定的一句话，表达类似的意思。（非问答模式）。

感谢！

**Comment by Morizeyao** [comment]
训练材料给什么，模型就会学习生成什么的规律。
按你的需求，每次提供给模型的应该是一对意思类似的句子对，预测的时候输入第一个句子，让他去续写第二个句子就行。
当然，这个思路需要试试，不一定能成。

**Comment by lexmen318** [comment]
感谢及时回复！

其实我的想法是通过大量的语料来生成，但就不知道如何在生成的时候怎么通过调整模型来影响输出，从而达到我的目的。

**Comment by JamesHujy** [comment]
我尝试过输入一个主题，生成相应主题的古诗词，效果还不错。
训练方法就是把每首古诗的题目作为一个序列的开始放到最前面。所以道理上还是给怎样的训练语料就会出怎样的训练结果

**Comment by maozezhong** [comment]
@JamesHujy 你好，请问你把题目放在开始位置的时候，有加分割标志吗？ 还是直接和古诗内容拼接？

**Comment by maozezhong** [comment]
如果是文本摘要生成或者标题生成任务，即给定大段文字生成标题或者摘要。单纯的拼接是否效果会弱，可能因为这是一个“长”+“短”预测“短”

**Comment by leizhu1989** [comment]
> 训练材料给什么，模型就会学习生成什么的规律。 按你的需求，每次提供给模型的应该是一对意思类似的句子对，预测的时候输入第一个句子，让他去续写第二个句子就行。 当然，这个思路需要试试，不一定能成。

@Morizeyao 你好，也就是比如我想训练问答，第一句输入问题，后面跟着回答结果，这样就可以了吗；例如：卷积神经网络在一张图上如何实现的？ 然后附上回答：xxxxxxx  ，是这样的吗？谢谢大佬
