### ISSUE TITLE
多gpu混合精度训练的问题

### ISSUE THREAD

**Issue by fengzuo97** [Morizeyao/GPT2-Chinese#32]
我使用自己的代码，大致实现是和作者一样的，多gpu单精度训练和单gpu混合精度训练都没问题，但是如果多gpu混合精度训练就会报arguments are located on different GPUs的错误，请问作者使用多gpu混合精度训练出现过类似的bug吗？

**Comment by fengzuo97** [comment]
作者还提到了fp16不收敛，我试验了可以收敛，使用wiki的1.3G语料，在v100上混合精度训练5个epoch，loss讲到3.2，和单精度基本一致，不过我使用的是50257的bpe，并不是bert tokenizer。另外在1080TI上也收敛，不过在1080TI上混合精度训练比单精度训练稍慢一些。

**Comment by Morizeyao** [comment]
多gpu的话，问题可能是[这个](https://github.com/huggingface/pytorch-transformers/pull/896)。
用BPE tokenizer做效果怎么样呀？

**Comment by fengzuo97** [comment]
谢谢，bpe tokenizer效果不错，最早之前是用bert tokenzier，效果并不是很好，loss有点难下降，不过我没有控制变量，中间还有一些其他的因素变动。

**Comment by Morizeyao** [comment]
介意分享一下设计中文bpe tokenizer的方案么？或者做个PR

**Comment by fengzuo97** [comment]
之前是用sentencepiece，但是这个不太灵活，不能方便的往词表中加词，后来就是在官方gpt2 tokenizer中改进的，思路也和英文的byte bpe 一致，因为公司保密的原因，不方便公开代码。

**Comment by Morizeyao** [comment]
ok，谢谢分享 :)
