### ISSUE TITLE
Undefined name 'running_loss' in ./train_single.py

### ISSUE THREAD

**Issue by cclauss** [Morizeyao/GPT2-Chinese#34]
flake8 testing of https://github.com/Morizeyao/GPT2-Chinese on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./train_single.py:184:21: F821 undefined name 'running_loss'
                    running_loss += loss.item()
                    ^
2371     F821 undefined name 'running_loss'
```

**Comment by Morizeyao** [comment]
fixed, thank you for bringing up the bug xD
