### ISSUE TITLE
生成的古诗中包含大量UNK

### ISSUE THREAD

**Issue by lijun20** [Morizeyao/GPT2-Chinese#36]
![image](https://user-images.githubusercontent.com/6458704/63661459-3d3b8c00-c7ed-11e9-8472-b961cea8282c.png)

**Comment by Morizeyao** [comment]
你好，训练古诗生成的话请使用词表 cache/vocab_guwen.txt 。
如果还不能解决的话，生成时请屏蔽UNK位置的logits，设为负无穷，就不会生成UNK了。

**Comment by lijun20** [comment]
> 你好，训练古诗生成的话请使用词表 cache/vocab_guwen.txt 。
> 如果还不能解决的话，生成时请屏蔽UNK位置的logits，设为负无穷，就不会生成UNK了。

谢谢回复，我试试
