### ISSUE TITLE
argparse中参数gradient_accumulation类型错误

### ISSUE THREAD

**Issue by xinfeng1i** [Morizeyao/GPT2-Chinese#38]
**错误原因**
`train.py` 脚本中第 57 行 `parser` 设置参数 `gradient_accumulation` 的类型为 `str`

> parser.add_argument('--gradient_accumulation', default=1, type=str, required=False, help='梯度积累')

会导致第 139 进行除运算时抛出类型错误，不能对 str 做除法

> total_steps = int(full_len / stride * epochs / batch_size / gradient_accumulation)

**更正建议**
在第 57 行设置参数 `gradient_accumulation` 的类型为 `int`

**Comment by Morizeyao** [comment]
感谢提议，这个问题是你发现的，可以你做个PR，我merge进来，这样你可以成为contributer。

**Comment by Morizeyao** [comment]
已修正

**Comment by xinfeng1i** [comment]
看到晚了，你已经更正了。下次有机会我再成为 contributor 吧，哈哈
