### ISSUE TITLE
运行train.py 的时候报错 module 'tensorflow.io' has no attribute 'gfile'

### ISSUE THREAD

**Issue by JiaLei123** [Morizeyao/GPT2-Chinese#47]
运行train.py 的时候报错 module 'tensorflow.io' has no attribute 'gfile'

**Comment by fengzuo97** [comment]
很有可能是tensorboard版本问题，卸载掉tensorboard，pytorch新版本中已经有了

**Comment by Morizeyao** [comment]
貌似需要安装tb-nightly

**Comment by JiaLei123** [comment]
果然，卸载了之前的tensorboard，并且安装了新的tensorboard后就Ok了
