### ISSUE TITLE
Bug: 文件指针没有被关闭

### ISSUE THREAD

**Issue by xinfeng1i** [Morizeyao/GPT2-Chinese#52]
**Bug Report**
在生成脚本 `generate.py` 中第 169 行，打开的文件指针 `samples_file ` 在使用完后没有被关闭，可能会造成句柄泄露。
> samples_file = open(args.save_samples_path + '/samples.txt', 'w', encoding='utf8')

**更正建议**
在退出循环前，显示关闭文件指针 `samples_file.close()`

**Comment by Morizeyao** [comment]
感谢提醒，你可以做个PR吗？这样可以成为contributer

**Comment by xinfeng1i** [comment]
> 感谢提醒，你可以做个PR吗？这样可以成为contributer

可以，我来提个 PR
