### ISSUE TITLE
BPE 使用

### ISSUE THREAD

**Issue by NiceMartin** [Morizeyao/GPT2-Chinese#54]
在说明文档中, 提到 “ 若使用BPE Tokenizer，需自己建立中文词表”
怎么理解? 

谢谢

**Comment by Morizeyao** [comment]
每个tokenizer都需要词表来支持，项目内有分字的词表（如vocab_small.txt）以及分词的词表（vocab_seg.txt)，但是BPE的词表没有提供，需要自行制作。

**Comment by NiceMartin** [comment]
> 每个tokenizer都需要词表来支持，项目内有分字的词表（如vocab_small.txt）以及分词的词表（vocab_seg.txt)，但是BPE的词表没有提供，需要自行制作。

谢谢回复
这个词表的内容就是 中文词语 吗, 如:
词1, 词2, 词3

**Comment by Morizeyao** [comment]
除了BPE之外是这样的，具体格式可以参考cache内文件

**Comment by NiceMartin** [comment]
> 除了BPE之外是这样的，具体格式可以参考cache内文件

谢谢
在初始化 BPE tokenizer时
full_tokenizer = get_encoder(args.encoder_json, args.vocab_bpe)
其中的args.encoder_json  的作用是什么?

**Comment by Morizeyao** [comment]
不知道，这个功能不是我添加的我无法回答...你可以先试试分词模式，效果不错的，如果有兴趣的话再试试sentencepiece的BPE model

**Comment by NiceMartin** [comment]
> 不知道，这个功能不是我添加的我无法回答...你可以先试试分词模式，效果不错的，如果有兴趣的话再试试sentencepiece的BPE model

好的, 感谢 !

**Comment by LeeCP8** [comment]
基于字分割，其实也不错的，基于词的话，个人觉得直接使用jieba分词，自己构建词典，提供token2ids及ids2tokens，效果应该也不错，毕竟jieba分词在中文的应用明显好于其它的。另外使用Google的Sentence Piece效果跟Jieba分词比起来，我自己作了测试，觉得一般，分词效果一般，以上纯属个人观点。

**Comment by Morizeyao** [comment]
嗯，我仓库里自带的是thulac分词，比jieba要慢不少。仓库里也提供了分好词的词表，以及自己制作词表的脚本。
总的来说分词模式效果比分字要好不少。

**Comment by fengzuo97** [comment]
get_encoder这个是参考open ai官方的gpt2代码写的，抱歉没有提供这两个文件，按照英文的模型，构建类似的中文的encoder.json和bpe文件即可，自由度很大
