### ISSUE TITLE
训练数据丢失问题

### ISSUE THREAD

**Issue by LeeCP8** [Morizeyao/GPT2-Chinese#55]
**采用分片切割的方式，分得越多，丢失的数据越多**
1 每个Piece所拥有的数据长度不一，在使用移动窗口分割数据时，会完全丢失数据，这部分数据（当然数据不多，小于seq_len）将永远不参与训练。分得越多，丢得越多。
2 在分batch时，不足以组成一个完整batch的数据将被丢失，当然这个可以通过多轮epoch来解决，但是通过shuffle，无法保证上一轮丢弃的数据一定会参与训练。此处丢失[0,seq_len*(batch_size-1)]，batch_size越大，丢失得越多。
3 stride的取值问题，会使得部分数据参与运算的次数高于其它数据，人为改变了数据原有的分布，请问怎么看待这个问题？
建议可通过基于步数分割成片，如每Piece包含多少步。而每步长=(seq_len-stride)+stride*batch_size，这样最多永久丢失一步数据[0,步长)，不想丢失，可人为补至完整一步。

**Comment by Morizeyao** [comment]
你观察的很仔细，这几个问题我考虑过，但是因为懒和代码稳定性考虑没有去动手。
1，这个问题我之前尝试使用最后一个切片最后加PAD的方式解决，但是因为有小bug被我搁置了。后来被某个PR作为废代码删掉了，我忘了是谁的PR...目前来说，解决方法是尽量减少num_pieces。
2，drop last是一种常见做法，没关系的。
3，stride会使一个piece的开始与结束处的文本被处理次数稍微少一点，我觉得解决方法还是尽量减少num_pieces。

**Comment by LeeCP8** [comment]
你好，代码是我删除的，不好意思，因为没有用到也没说明，而且感觉有问题，所以我直接删除。基于步数做分割，最多丢失一个batch，你可以试试，所以在分batch也不存在drop last问题。
另外，学习速率可调节模式，因为默认的流程是pytorch-transformer中的例子，使用梯度累积改变学习速率，而且是基于lambda，感觉没有pytorch自身提供的torch.optim.lr_scheduler.StepLR学习速率调节算法方便。
最后，使用梯度累积输出时存在问题，具体问题我没记录。

**Comment by Morizeyao** [comment]
嗯..梯度积累是什么问题？我最近没用梯度积累，如果有bug的话可能也没机会发现

**Comment by fengzuo97** [comment]
这一块感觉作者做复杂了，我用的每个样本的长度是1024，将数据截断为1024的倍数，然后reshape成（-1，1024），用pytorch的DataLoader，更加直观方便。关于分piece，我认为作用主要在于将数据转成id时可以使用多进程加快速度，因为如果数据非常大，这一块很耗时，所以一般使用8个或者16个，转成id后，合并。

**Comment by fengzuo97** [comment]
> 你好，代码是我删除的，不好意思，因为没有用到也没说明，而且感觉有问题，所以我直接删除。基于步数做分割，最多丢失一个batch，你可以试试，所以在分batch也不存在drop last问题。
> 另外，学习速率可调节模式，因为默认的流程是pytorch-transformer中的例子，使用梯度累积改变学习速率，而且是基于lambda，感觉没有pytorch自身提供的torch.optim.lr_scheduler.StepLR学习速率调节算法方便。
> 最后，使用梯度累积输出时存在问题，具体问题我没记录。

不明白你的使用梯度累计改变学习率是什么意思，作者项目中使用的是warm up调节学习率，所以也就不需要用到lr_scheduler.StepLR

**Comment by LeeCP8** [comment]
首先，利用pytorch提供的DataLoader来加载分批加载并训练数据，这个我早上刚刚看了，所以我才提交了最新的PR，DataLoader处理数据时，对于无法组成一个完整的Batch，也是可以声明进行训练，所以我把最后的Batch也添加进去，当然作者觉得没必要。所以总的来说，pytorch已经提供了所有基础函数，很多没有必要实现，直接使用DataLoader的确是很方便的。
 作者这个例子，基本就是pytorch-transformer示例的内容，里面使用的warmup进行调节学习率，这个我知道，通过一个累积次数来更改学习率，这个跟lr_scheduler.StepLR作用是相同的，当然外加一个速率调节(0,1,0)，但是直接运行例子是存在一些问题的，所以我才说改用lr_scheduler.StepLR更加方便。因为Pytorch本身已经提供了这些算法，毕竟很多别人封装好的东西，没完全理解，往往比自己实现更难使用。

**Comment by fengzuo97** [comment]
加不加最后一句几乎几乎没什么影响。
关于学习率调节的，直接运行会有什么问题吗？建议在打印时将学习率带上，可以观察学习率是否正确的变化。本质上用lr_scheduler.StepLR也可以实现warm up，但是有点多此一举，根据全局的step来指定learning step更加方便直观。

**Comment by LeeCP8** [comment]
其实有没有影响，这个问题取决于数据本身，主观认知没有意义，但是我们应该让数据客观体现自身。另外lr_scheduler.StepLR就是通过全局Step + 系数来控制一个learning rate。

**Comment by LeeCP8** [comment]
> 加不加最后一句几乎几乎没什么影响。
> 关于学习率调节的，直接运行会有什么问题吗？建议在打印时将学习率带上，可以观察学习率是否正确的变化。本质上用lr_scheduler.StepLR也可以实现warm up，但是有点多此一举，根据全局的step来指定learning rate更加方便直观。
直接一切默认，不会有什么问题，但是模型默认的warmup=2000，lr=1.5e-4，假设此时总的步数<2000，那么实际lr=[0,1.5e-4)之间，步数越小，lr越小，会出现难收敛的问题。
假设我一开始想让模型收敛得快一些，设lr=0.001,那么实际也得到2000步时，lr才到真正的0.001，之前都比这小，与lr参数的初衷相违背，所以warmup默认值，建议设为0。
最后，输出不一致问题。假设设置了gradient_accumulation=4，而log_step默认，那么每隔4次，输出一个loss，但是log_step默认为1，每次都输出loss=0，当然对结果没有影响，但是感觉...
