### ISSUE TITLE
文本学习效果请教

### ISSUE THREAD

**Issue by chiangandy** [Morizeyao/GPT2-Chinese#6]
由于我的硬体上无法训练BERT还无法能验证，由于我有一个项目要对短视频剧本生成AI写作的需求，之前我用LSTM 模型来实作，但是只能保有句子本生身通顺但是句子间或是多句文章时就看不出主题取向效果有点不能接受。看到大大的BERT模型燃起一丝希望，想请教您的过往经验如果用这BERT模型是否能解决LSTM的剧本生成的问题？

感谢赐教～

**Comment by Morizeyao** [comment]
这个不是BERT。GPT2相比于LSTM的模型主要优点在于文本的远距离记忆能力要强很多，比如说文章会列举第一，第二，第三，第四等若干点。从你的描述上看，GPT2的模型是可以解决你的需求的。
具体的GPT2与传统LSTM文本生成的区别可以参考https://github.com/minimaxir/gpt-2-simple内Differences Between gpt-2-simple And Other Text Generation Utilities部分。

**Comment by chiangandy** [comment]
不好意思我说错了，没错是说GPT2 是否可以解决LSTM的问题，听君一言感到有信心多了，非常感谢～我再研究看看
