### ISSUE TITLE
gradient_accumulation及warmup_steps参数问题

### ISSUE THREAD

**Issue by LeeCP8** [Morizeyao/GPT2-Chinese#60]
模型默认的warmup=2000，lr=1.5e-4，假设此时总的步数<2000，那么实际lr=[0,1.5e-4)之间，步数越小，lr越小，会出现难收敛的问题。
假设我一开始想让模型收敛得快一些，设lr=0.001,那么实际也得到2000步时，lr才到真正的0.001，之前都比这小，与lr参数的初衷相违背，所以warmup默认值，建议设为0。
最后，输出不一致问题。假设设置了gradient_accumulation=4，而log_step默认，那么每隔4次，输出一个loss，但是log_step默认为1，每次都输出loss=0，当然对结果没有影响，但是感觉...

**Comment by Morizeyao** [comment]
learning rate就是这么工作的呀，否则会陷入局部最优解

**Comment by Morizeyao** [comment]
gradient_accumulation确实是个bug...呃

**Comment by LeeCP8** [comment]
> learning rate就是这么工作的呀，否则会陷入局部最优解

lr的确是这么更新的，但是作为默认的参数，应该保持通用，如果使用者自己去调整参数，那么使用者需要了解参数背后的作用，所以我建议为0，当然这只是建议。
另外那个输出，有时间改改吧。
