### ISSUE TITLE
generate.py中参数batch_size的作用

### ISSUE THREAD

**Issue by LeeCP8** [Morizeyao/GPT2-Chinese#61]
从代码的逻辑上看，重复输出样本，实在不知道有什么作用，还是作者想批量生成，最后没实现？如果作者有时间的话，也请重新审视一下代码吧，细节上有太多问题了，虽然我想改，但是有些东西，不是我实现的，避免误改，还是请作者自己修改吧。

**Comment by Morizeyao** [comment]
generate.py的代码大部分不是我写的，后来的修改版又不方便放上来...

**Comment by LeeCP8** [comment]
功能就是另一位朋友添加的，我做了整合，并删除了一些无用的代码，剩下的都是原装的，作者的意思是，你自己提交的代码大部分也是别人写的？

**Comment by Morizeyao** [comment]
嗯，generate.py的代码大部分不是我写的

**Comment by LeeCP8** [comment]
有时间请作者看看stable版本吧，审视一下代码，当然我也理解有些代码不宜公开，但改掉一些逻辑错误，还是有必要的，也谢谢你的回复。
