### ISSUE TITLE
文章摘要生成

### ISSUE THREAD

**Issue by maozezhong** [Morizeyao/GPT2-Chinese#63]
@Morizeyao 感谢分享代码。请问下文本摘要生成，即seq2seq任务用gpt2该怎么修改？ 是直接标题和内容拼接输入吗？

**Comment by Morizeyao** [comment]
摘要的话，我猜应该是：
[MASK]正文[SEP]摘要[CLS]
这样的格式吧
然后预测的时候输入[CLS][MASK]正文[SEP]，会续写摘要。
我没做过，可以试试看

**Comment by maozezhong** [comment]
@Morizeyao 好的，多谢，我尝试下

**Comment by chenjun0210** [comment]
@Morizeyao @maozezhong  请问几个问题
1. 我看代码中有把正文\n 都替换成了[SEP] , 那 正文和摘要之前用[SEP] 会有歧义影响吗？还有要自定义分割符如[Abstarct] ，但是这样tokenize 不会把这种符号作为整体切，我试着把这种分隔符加入到字典中，也没有生效，还是拆开了。
2. 新闻正文内容特别长（中文语料），超过1024字符 ，后来处理成直接截取到1024 ，这样会丢失很多正文信息，请问有其他好的方法处理吗？ 想着如果用分词来处理，但是这种vocab_size 的维度应该要设置很大吧，不然默认5万个词，不够生成摘要用。

**Comment by Morizeyao** [comment]
1，使用单独分隔符是可以的，都用SEP也可以。如果你要添加额外的特殊符号的话，貌似需要改动一些代码了。
2，要么增加模型长度，要么使用分词模式。新闻正文特别长的话，推荐使用分词模式，然后根据语料生成专用词表来训练。当然，分词导致的OOV问题依然无法完全解决，可以尝试使用albert的方案减小embedding matrix大小。

**Comment by lewiswu1209** [comment]
> @Morizeyao @maozezhong 请问几个问题
> 
> 1. 我看代码中有把正文\n 都替换成了[SEP] , 那 正文和摘要之前用[SEP] 会有歧义影响吗？还有要自定义分割符如[Abstarct] ，但是这样tokenize 不会把这种符号作为整体切，我试着把这种分隔符加入到字典中，也没有生效，还是拆开了。
> 2. 新闻正文内容特别长（中文语料），超过1024字符 ，后来处理成直接截取到1024 ，这样会丢失很多正文信息，请问有其他好的方法处理吗？ 想着如果用分词来处理，但是这种vocab_size 的维度应该要设置很大吧，不然默认5万个词，不够生成摘要用。

三年了，相信你的问题得到解决了，我也遇到了自定义特殊token的问题，后来查阅了好多资料才找到正确的方法，在这里记录一下，以便能帮助到需要的人:
1、修改vocab.txt；
2、修改代码：
tokenizer = BertTokenizer.from_pretrained("")
tokenizer.add_special_tokens( {'additional_special_tokens':['[token1]','[token2]']} )
