### ISSUE TITLE
我有预感，这个技术会跟deepfake一样，逐渐会出现在大众的视野当中

### ISSUE THREAD

**Issue by yzjkeke** [Morizeyao/GPT2-Chinese#64]
比如说这个标题：震惊，人工智能竟然让李白活过来了！或者是：起点作者的末日？人工智能竟然能编写小说！随着gpu性能的提升还有人工智能asic单元的出现，未来有可能会普及，这个东西对于世界的影响绝对比deepfake要大。（本人观点，不喜勿喷）

**Comment by BiEchi** [comment]
好家伙,快去看GPT-3
