### ISSUE TITLE
关于在训练文本里添加标签的想法

### ISSUE THREAD

**Issue by hughqiu** [Morizeyao/GPT2-Chinese#68]
如果在训练文本里面自己添加类似换行新文章的标签，将题目，写作要求和文体标签在训练文本中，再在词表里添加标签，请问最后训练出来标签是否会起作用呢？谢谢

**Comment by Morizeyao** [comment]
有作用，之前在训练生成特定题材古诗中体现了一定的作用

**Comment by Raxxor** [comment]
能否分享一下在特定诗词中的具体操作跟结果呢？ 考虑按词牌生成词，或者生成七言，五言律诗，绝句之类的场景，也没想好如何操作比较合适

**Comment by hughqiu** [comment]
> 有作用，之前在训练生成特定题材古诗中体现了一定的作用

谢谢了，准备开始练一个大规模的作文集。
