### ISSUE TITLE
对 total_steps 的估算?

### ISSUE THREAD

**Issue by xinfeng1i** [Morizeyao/GPT2-Chinese#69]
目前在训练脚本中对训练步数按照如下方式估算
> total_steps = int(full_len / stride * epochs / batch_size / gradient_accumulation)

其中前面一部分 `full_len/stride` 是对训练样本数的估计，然这种估算方式忽略了滑动窗口本身的大小，更准确训练样本个数应该为：

```
train_examples_num = (full_len - n_ctx + stride) // stride   # drop extra input_ids
```
然后，如果 `gradient_accumulation = 1`，则

```
total_steps = (train_examples_num // batch_size ) * epochs   # drop last batch if not divisible
```

如果 `gradient_accumulation = 1`，则
```
total_steps = ( (train_examples_num // batch_size ) * epochs ) // gradient_accumulation
```

大家觉得有必要追求更加精准的计算方式吗？

**Comment by Morizeyao** [comment]
类似之前有朋友提到的边界问题，对训练步数的估算可以改进但是实际效果应该不大。如果有心的话可以做个pr我拉进来。
