### ISSUE TITLE
训练好的模型移至CPU上执行

### ISSUE THREAD

**Issue by chiangandy** [Morizeyao/GPT2-Chinese#7]
想请问一下如果在有GPU的机器上训练好模型后，在产生内文时是否可以移至CPU上来运行？我是知道诸如LSTM跟RNN是都可以把tensor跟model移至CPU来执行，由于GPT-2有预训练过不知道是否也可以训练好移至CPU上运行？

**Comment by Morizeyao** [comment]
可以的，但是运行速度不保证
