### ISSUE TITLE
生成效果的疑问

### ISSUE THREAD

**Issue by caishiqing** [Morizeyao/GPT2-Chinese#71]
目前训练的模型大小好像都比语料本身还大，有没有检查过生成的内容是不是和原语料重复度很高，模型只是把语料压缩记忆下来？

**Comment by lioyou** [comment]
感觉模型生成的可读性片段，并非无中生有，在训练的语料中可以找到，似乎更像是片段组合，重复度看情况。

**Comment by Morizeyao** [comment]
模型有可能会完全记忆原语料。预测的时候控制参数temperature，topk与topp可以限制生成的随机性。
简单说的话，直接取argmax会导致生成内容有很高概率完全背诵训练材料。

**Comment by caishiqing** [comment]
@Morizeyao 嗯嗯，是的，在小语料库下基本上去argmax会把训练语料的原文给生成出来。

**Comment by lewiswu1209** [comment]
那个中文歌词的模型就会抄语料，把张信哲的整首歌都给抄出来了，后来调temperature参数才不抄的，但是会生成很长的句子，就是那种能把歌手憋死的那种^_^
