### ISSUE TITLE
训练数据处理的疑问

### ISSUE THREAD

**Issue by caishiqing** [Morizeyao/GPT2-Chinese#72]
for ids in batch:
      int_ids_for_labels = [int(x) for x in ids]
      int_ids_for_inputs = [int(x) for x in ids]
      batch_labels.append(int_ids_for_labels)
      batch_inputs.append(int_ids_for_inputs)

这段代码有点疑问，输入输出一样？那不变成自编码器了？输出不应该是输入的one right shift吗？

**Comment by lioyou** [comment]
请参考：https://github.com/Morizeyao/GPT2-Chinese/issues/66#issuecomment-533364130
计算时误差时pytorch-transformer，内部做了位置切换

**Comment by Morizeyao** [comment]
嗯

**Comment by caishiqing** [comment]
@lioyou 原来如此，谢谢！

**Comment by lioyou** [comment]
所以代码可以处理成这样子，input与label是一样的，减少空间浪费：
```python
batch_inputs = []
for ids in batch:
    int_ids_for_inputs = [int(x) for x in ids]
    batch_inputs.append(int_ids_for_inputs)
batch_inputs = torch.tensor(batch_inputs).long().to(device)
 #  forward pass
outputs = model.forward(input_ids=batch_inputs, labels=batch_inputs)
```

**Comment by Morizeyao** [comment]
你说的没错

**Comment by Morizeyao** [comment]
已做更正
