### ISSUE TITLE
如何做限定体裁的生成

### ISSUE THREAD

**Issue by MrRace** [Morizeyao/GPT2-Chinese#73]
对于生成古诗，怎么生成限定体裁的古诗？比如七言绝句，七言律诗？如何在一个模型中控制生成？如果分开训练成2个模型，显得挺繁琐。我看官方的示例中是有限定体裁的生成例子的。

**Comment by Morizeyao** [comment]
使用题材加分隔符加正文的方式训练，预测的时候给出题材加分隔符作为开头
