### ISSUE TITLE
請問data/tokenized的文件去哪取得

### ISSUE THREAD

**Issue by cbt36594** [Morizeyao/GPT2-Chinese#74]
因為使用說明沒這部分
但是想訓練的時候出現data/tokenized/tokenized_train_1.txt內的檔案找不到
請問這地方改怎麼使用

**Comment by Rezirv** [comment]
就是主目录下的tokenizations

**Comment by Morizeyao** [comment]
需要加--raw运行train.py，生成tokenized文件哦

**Comment by cbt36594** [comment]
> 需要加--raw运行train.py，生成tokenized文件哦

原來如此~研究好久~感謝了
