### ISSUE TITLE
训练的时候总是出现这个issue

### ISSUE THREAD

**Issue by JiaLei123** [Morizeyao/GPT2-Chinese#75]
Token indices sequence length is longer than the specified maximum sequence length for this model (1146 > 1024). Running this sequence through the model will result in indexing errors

使用的语料数据https://github.com/brightmart/nlp_chinese_corpus

**Comment by DarylLei** [comment]
这个是数据tokenized时，原始文本长度超过设定值，给出的提示。可以不设置该参数。自己做数据长度控制。
![image](https://user-images.githubusercontent.com/35752878/66618100-82374880-ec0a-11e9-8efe-4bfb323e71a8.png)

**Comment by Morizeyao** [comment]
这个提示是pytorch transformer里会提示的，我没去改他，所以无视就好
