### ISSUE TITLE
训练损失值得问题

### ISSUE THREAD

**Issue by DarylLei** [Morizeyao/GPT2-Chinese#77]
您好，请问训练过程中，你们的损失值能降到多少？
我的损失值，降到5点多就不再下降，迭代了很久，但感觉没有收敛

![EAB55737-A257-45fb-A913-C58476CB094F](https://user-images.githubusercontent.com/35752878/66558051-7e151780-eb85-11e9-912d-efa47450defc.png)

**Comment by Morizeyao** [comment]
一般对小语料可以降到零点几，对于3G的语料可以降到2到3的样子，5有点大了，你的训练语料和模型大小，训练参数分别是多少？

**Comment by DarylLei** [comment]
> 一般对小语料可以降到零点几，对于3G的语料可以降到2到3的样子，5有点大了，你的训练语料和模型大小，训练参数分别是多少？

我的训练语料纯文本4.7G，tokenized后有8G，模型参数9千多万，别的参数基本都是默认，学习率1.5e-4，别的没改动啥啦

**Comment by Morizeyao** [comment]
emm，你是什么样的机器迭代了多久？按你的情况我感觉貌似没啥问题，试试看生成的效果呢？

**Comment by AaronZhangL** [comment]
@Morizeyao 请问您使用的机器配置是怎样的？训练时间大概是多长？我准备用AWS的EC2实验一下，但是不知道哪个配置比较合适，所以请教一下，以做参考。

**Comment by Morizeyao** [comment]
训练3G语料的模型，我用四块2080ti的机器训练了两周的样子。

**Comment by mzjuin** [comment]
> 训练3G语料的模型，我用四块2080ti的机器训练了两周的样子。

打算发布模型吗？

**Comment by Morizeyao** [comment]
> > 训练3G语料的模型，我用四块2080ti的机器训练了两周的样子。
> 
> 打算发布模型吗？

这个模型我没法发布
