### ISSUE TITLE
微信交流群

### ISSUE THREAD

**Issue by Morizeyao** [Morizeyao/GPT2-Chinese#78]
各位好。因为存在很高呼声，微信交流群已经建立，欢迎加入。

update: 微信群已满，请加QQ交流群912434813。

update: QQ交流群已关闭。

**Comment by Anida-qin** [comment]
你好，微信群，用户不存在

**Comment by jason5675** [comment]
上面那个微信二维码扫码后一直显示查找失败，无法添加。我有个问题想请教：model_config.json中的n_ctx是指什么意思？

**Comment by Morizeyao** [comment]
是指模型长度，小熊貌似异常了

**Comment by jason5675** [comment]
Thanks. 小熊应该是异常了。想入群，求攻略。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zeyao Du"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月3日(星期天) 晚上6:45
收件人:&nbsp;"Morizeyao/GPT2-Chinese"<GPT2-Chinese@noreply.github.com&gt;;
抄送:&nbsp;"周存"<526890100@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Morizeyao/GPT2-Chinese] 微信交流群 (#78)




是指模型长度，小熊貌似异常了

**Comment by Halfwaygo** [comment]
> 是指模型长度，小熊貌似异常了

我也想问这个问题

**Comment by Halfwaygo** [comment]
> 上面那个微信二维码扫码后一直显示查找失败，无法添加。我有个问题想请教：model_config.json中的n_ctx是指什么意思？

我也想问这个问题

**Comment by Morizeyao** [comment]
是指模型处理单样本的最大长度

**Comment by chenzelong** [comment]
我想请教一下，项目的中文分词是字符还是单词？
如果是字符形式的分词，为什么词典里面会存在单词？
如果是单词形式的分词，如何转换为字符形式的分词？

**Comment by logcy** [comment]
怎么加到你们的群里面？我关注了kcrobot输入nlp没反应

**Comment by Morizeyao** [comment]
> 怎么加到你们的群里面？我关注了kcrobot输入nlp没反应

你好，很抱歉微信群人满500暂时没hc了

**Comment by kaikefly** [comment]
请问有 hughqiu 散文模型的训练语料吗？

**Comment by micklexqg** [comment]
群满了，那怎么加呢

**Comment by Morizeyao** [comment]
微信群已满，请加QQ交流群912434813

**Comment by hackyes** [comment]
有没有人做一下教程啊，我用windows，python3.6 ，生成的都是乱码

**Comment by Tao-Ya** [comment]
生成乱码，用自己train.json数据生成的词库时而会出现很多[UNK]，语句很乱；用作者现有的词库会出现生成很多的乱码，目前不清楚是参数的问题还是什么问题，有点懵...

**Comment by yc-cui** [comment]
> 微信群已满，请加QQ交流群912434813

QQ群搜不到？

**Comment by miko8422** [comment]
你们qq群解散了吗？

**Comment by Creative-Ataraxia** [comment]
> 你们qq群解散了吗？

有没有人要重新发起一个微信群之类。。

**Comment by pureloveljc** [comment]
有没有人要重新发起一个微信群之类。。

**Comment by fightingfish008** [comment]
有群？

**Comment by yiyepiaoling0715** [comment]
> 

搜不到， 我qq  1015731284 ，麻烦拉一下?

**Comment by leafone123** [comment]
找不到组织，我组了一个Q群：698954213

**Comment by Solaina888** [comment]
bin格式的模型文件怎么调用
