### ISSUE TITLE
generate时如果设置了生成长度之后生成的内容会被截断，如何解决

### ISSUE THREAD

**Issue by wusj18** [Morizeyao/GPT2-Chinese#80]
![image](https://user-images.githubusercontent.com/46401656/67146793-1ff0de80-f2c1-11e9-82fa-09ad5a8ef972.png)
比方说这样，10里面的内容就没有生成完整直接被截断了，请问是否有更好的办法限制生成长度呢？非常感谢！

**Comment by lioyou** [comment]
例子：
问题：怎样避免生成不完整的句子呢？
回答：可以通过设置特殊标记，声明结尾，最后生成时，判断标记并自动停止。
训练时：
input：【问题】怎样避免生成不完整的句子呢？【回答】可以通过设置特殊标记，声明结尾，最后生成时，判断标记并自动停止。【END】
生成时：
input：【问题】怎样避免生成不完整的句子呢？
output： if output == [END] break
训练时，你传递的特征，模型是会学习到的，所以当生成时，同样会生成END标记，那么判断一下并停止就可以了，当然生成效果取决于你的训练结果。
或者你的模型已经在每个句子尾部添加了换行，那么你判断一下换行标记也是一个折中方法，再一次强调一下，生成效果取决于你的训练结果。
训练结果很差，loss很高，就别想生成好看的回答。 
欢迎交流，谢谢！

**Comment by Morizeyao** [comment]
有办法，改一下代码，设置遇到cls就结束生成，这样就可以提前在生成完一篇完整文章的时候结束了
