### ISSUE TITLE
Fine tuning on custom language

### ISSUE THREAD

**Issue by Radeeswar** [Morizeyao/GPT2-Chinese#84]
Hi @Morizeyao , Can you tell me how to fine tune on own languages. Since i tried to train it on Telugu language by creating my own vocab using make_vocab.py and results are poor( Returning mostly 
 'unk' characters. Any suggestions?

**Comment by Morizeyao** [comment]
The code is not designed to train or generate on a custom language, but you can do it after some modifications.

The key is to make a vocab file. make_vocab.py is designed for Chinese language so you need to create your vocab.txt separately.

If Telugu language is like Chinese then it should have characters. Place the special tokens and Telugu characters in vocab.txt, one line one token. Here you should use character level vocabulary not word level.

After completed making the vocab.txt, make your own train.json file and use train.py to train the model. I think most of the default parameters should be fine but you need to make sure vocab parameter points to your custom vocab file.

I am sorry I didn't expect non-Chinese users of this repo, so most of the comments are in Chinese. If you encounter any problems please let me know. :)

**Comment by Radeeswar** [comment]
> The code is not designed to train or generate on a custom language, but you can do it after some modifications.
> 
> The key is to make a vocab file. make_vocab.py is designed for Chinese language so you need to create your vocab.txt separately.
> 
> If Telugu language is like Chinese then it should have characters. Place the special tokens and Telugu characters in vocab.txt, one line one token. Here you should use character level vocabulary not word level.
> 
> After completed making the vocab.txt, make your own train.json file and use train.py to train the model. I think most of the default parameters should be fine but you need to make sure vocab parameter points to your custom vocab file.
> 
> I am sorry I didn't expect non-Chinese users of this repo, so most of the comments are in Chinese. If you encounter any problems please let me know. :)


Thank you @Morizeyao , for your reply. Yes i think i need to change vocab file by generating in own way.
