### ISSUE TITLE
请问只能从零开始训练中文版本的GPT2模型吗？不能基于openai已放出的模型做Finetune吗？

### ISSUE THREAD

**Issue by jason5675** [Morizeyao/GPT2-Chinese#87]
请问只能从零开始训练中文版本的GPT2模型吗？不能基于openai已放出的模型做Finetune吗？

**Comment by Morizeyao** [comment]
简单说的话是不行的，因为openai做的是英文版，词表不同，语言不通。
复杂说的话，中间层是可以复制过来用的，但是得改一些代码。
