### ISSUE TITLE
readme里说可以用BPE tokenizer，但是其实目前并不支持啊。

### ISSUE THREAD

**Issue by jason5675** [Morizeyao/GPT2-Chinese#89]
readme里说可以用BPE tokenizer，但是其实目前并不支持啊。

**Comment by Morizeyao** [comment]
BPE模式是群众贡献的，你说不支持的是sentencepiece的BPE吗？

**Comment by Morizeyao** [comment]
emmm我看了一下，确实bpe模式被我暂时移除了，我把readme里对应的条目做一下修改。

**Comment by jason5675** [comment]
不是。没有词典表。而且也没法知道如何生成BPE格式的词典。

**Comment by Morizeyao** [comment]
使用BPE需要略微修改train.py，词典的话要用sentencepiece根据语料生成一下

**Comment by jason5675** [comment]
GPT2的词典是BPE格式，但是跟BERT的词典txt格式差别很大啊。怎么能知道如何生成GPT2的BPE格式的词典呢？sentencepiece在哪呀？

**Comment by Morizeyao** [comment]
GPT2带的BPE词典是英文的，所以没法直接用于中文的GPT2，所以在本项目中我使用了BERT的tokenizer。如果用BPE模式的话，使用的是第三方的sentencepiece库，也与GPT2英文版不同。

**Comment by Morizeyao** [comment]
已修改项目描述中与事实不符条目。
