### ISSUE TITLE
请教体育新闻的语料数量

### ISSUE THREAD

**Issue by chiangandy** [Morizeyao/GPT2-Chinese#9]
我有看到您新一版的训练成果有个体育新闻部分，想请教一下这训练的语料准备是多少的体育新闻数量？ 每则新闻大约有多少字？

感谢～

**Comment by Morizeyao** [comment]
需准备体育新闻约300MB，新闻长度1000字左右，语料来自于[http://thuctc.thunlp.org/#%E8%8E%B7%E5%8F%96%E9%93%BE%E6%8E%A5](url)
