### ISSUE TITLE
Create vocab.bpe !

### ISSUE THREAD

**Issue by ngocpham97** [Morizeyao/GPT2-Chinese#90]
Can you tell me the way to create vocab.bpe, please ???

**Comment by Morizeyao** [comment]
For vocab.bpe I'm afraid there is currently no easy way to create it.
If yuo want to use BPE mode you probably need to use Sentencepiece library and then modify some train.py codes.

**Comment by ngocpham97** [comment]
Yep. I  used Sentencepiece library to make file encoder.json but now I have no idea to make vocab.bpe

**Comment by Morizeyao** [comment]
There should be a model file and a vocab file after you have done the training process of Sentencepiece.
I haven't used Sentencepiece in practice yet so correct me if I am wrong :)

**Comment by ngocpham97** [comment]
Yes. There are .model and .vocab file after traning Sentencepiece and I used .vocab to make encoder.json same as  OpenAI GPT-2 model
