### ISSUE TITLE
认为这段代码有重大bug

### ISSUE THREAD

**Issue by jason5675** [Morizeyao/GPT2-Chinese#91]

**Comment by jason5675** [comment]
@Morizeyao 上楼的问题大佬怎么看呀？

**Comment by Morizeyao** [comment]
没感觉有问题，samples随机是打乱的sample，不是tokens，stride的设计引入重叠部分也不会影响训练，反而会解决切分句子的问题

**Comment by jason5675** [comment]
> 没感觉有问题，samples随机是打乱的sample，不是tokens，stride的设计引入重叠部分也不会影响训练，反而会解决切分句子的问题
我怎么觉得samples里面存的是tokens呢，555.。。。。切分句子不可以根据[CLS]来切吗？

**Comment by jason5675** [comment]
stride貌似没啥用呢，除了你说的解决切分句子问题。。。right？

**Comment by jason5675** [comment]
那我先把问题清一下。打乱samples和加stride有什么理论依据吗or有什么考量吗？ @Morizeyao

**Comment by lioyou** [comment]
@jason5675：你知道训练的步长吗？训练的文本长度是有限制的，并非随意长度的，假设你说的以【CLS】作分割，请问你怎样保证长度刚好等于步长，长了还是要分割，短了还要填补，所以【CLS】对分割没有意义，文本的分割单位是步长，不是其它自定义分割标记。
1 stride的意义：既然文本要分割成指定步长，那么分割点就会将前后两个字的关系分离（训练的原理就是用上一个字结合前文，预测下一个字），这样人为破坏了这两个字的关系，所以stride可以将被分割的两个字再组合成完整的步长再训练。
2 samples打乱：如果不打乱，训练结果有可能会出现波动不收敛或者收敛到局部最优值。
