### ISSUE TITLE
Undefined name 'encoder_path' in bpe_tokenizer.py

### ISSUE THREAD

**Issue by cclauss** [Morizeyao/GPT2-Chinese#93]
https://github.com/Morizeyao/GPT2-Chinese/blob/master/tokenizations/bpe_tokenizer.py#L128

[flake8](http://flake8.pycqa.org) testing of https://github.com/Morizeyao/GPT2-Chinese on Python 3.8.0

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./tokenizations/bpe_tokenizer.py:128:27: F821 undefined name 'encoder_path'
        return Encoder_SP(encoder_path)
                          ^
1     F821 undefined name 'encoder_path'
1
```

**Comment by Morizeyao** [comment]
fixed
