### ISSUE TITLE
为什么train_simple也是读取json的逻辑？

### ISSUE THREAD

**Issue by jinfagang** [Morizeyao/GPT2-Chinese#94]
不是说train_simple事单个文本文件吗，按照json的格式读取会出错

**Comment by Morizeyao** [comment]
啊？train_single的话，train.json里也得是列表的，只不过列表只有一个元素

**Comment by jinfagang** [comment]
我觉得不是很有必要，单个txt应该也行？最主要是json在parse的时候 "" 引号容易出问题，文本里面的符号太多太复杂

**Comment by Morizeyao** [comment]
可以的，但是要改一点点代码
