### ISSUE TITLE
单GPU训练应该该哪些参数

### ISSUE THREAD

**Issue by jinfagang** [Morizeyao/GPT2-Chinese#95]
batchsize修改到了2还是会OOM，除了这里还有哪些参数需要修改在单卡上训练吗 (8G)

**Comment by jason5675** [comment]
同问

**Comment by jason5675** [comment]
GPU训练的代码train.py是有bug的，很严重。一走到forward函数，GPU使用内存就飙升到15G左右（batchsize=200，每行是一个大概10个字的句子）。我的一块GPU16G，第一次调用forward就直接占用15G，训练没几次，就直接报OOM。

**Comment by Morizeyao** [comment]
调小batch size，调小模型结构，或者换更大显存的显卡

**Comment by jinfagang** [comment]
@jason5675 初试了一下，train_simple也有bug，generate也有bug，download那个散文的模型是无法生成的，当然这和transforms有关或者我打开的方式不对

**Comment by Morizeyao** [comment]
我们在群里玩的很开心啊，要不加交流群看看你使用的问题出在哪？

**Comment by jinfagang** [comment]
@Morizeyao Sure, let me add u

**Comment by lioyou** [comment]
@jinfagang @jason5675 
>  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 12,
  "n_positions": 1024,

- 我薅了Google羊毛时的配置，batch_size=2时，梯度累积16（相当于batch_size=32，这个项目梯度累积有问题，用时自己改吧），完全可以训练，用的是GPU（12G实为11点多）。
- 不过资本不是那么好糊弄的，时间一长（一天多），就直接禁止我使用资源了，再加上翻墙实在太累了，因为工具不稳定没买（老断），采用曲线救国的方式，将数据上传到github，将github中的数据下载到Drive中，最后将模型上传到Github中，容量超了，需要用到外部插件（限制1G，又得买），然后再下载到本地计算机，最后实在不想玩了。
- 但是那速度真香啊，特别只能用CPU或者本机那不够塞牙缝的GPU的时候，不得不感叹！另外不要完全压榨全部GPU空间，留下一些空间，不然用模型生成时，需要更多的GPU资源，运行不起来，那就GG了。

**Comment by jason5675** [comment]
好的谢谢 @ lioyou

**Comment by jinfagang** [comment]
@lioyou  梯度累计改了哪里？

**Comment by lioyou** [comment]
@jinfagang 你好，我用的是自己的项目，但是核心的东西跟这个库是一样的（改得太多了，无法复制给大家，请见谅），问题可以参考 #70 ，需要自己看一下代码，然后修改。
