### ISSUE TITLE
怎么老是报gpu内存溢出。训练几百步后就报。训练预料是一行一句话，总共也就50w行。

### ISSUE THREAD

**Issue by jason5675** [Morizeyao/GPT2-Chinese#96]
RuntimeError: CUDA out of memory. Tried to allocate 48.00 MiB (GPU 0; 15.90 GiB total capacity; 14.18 GiB already allocated

**Comment by Morizeyao** [comment]
模型调小点，batch size调小点，显存不足和语料总数没关系
