### ISSUE TITLE
train.json这么填，是有问题的。正确的格式是？

### ISSUE THREAD

**Issue by jason5675** [Morizeyao/GPT2-Chinese#97]
比如把整个小说直接拷到train.json中，然后作为一个list的元素。
    ["《斗破苍穹》

    第一章 陨落的天才

    “斗之力，三段！”

    望着测验魔石碑上面闪亮得甚至有些刺眼的五个大字，少年面无表情，唇角有着一抹自嘲，紧握的手掌，因为大力，而导致略微尖锐的指甲深深的刺进了掌心之中，带来一阵阵钻心的疼痛…

    “萧炎，斗之力，三段！级别：低级！”测验魔石碑之旁，一位中年男子，看了一眼碑上所显示出来的信息，语气漠然的将之公布了出来…
     中年男子话刚刚脱口，便是不出意外的在人头汹涌的广场上带起了一阵嘲讽的骚动。

    “三段？嘿嘿，果然不出我所料，这个“天才”这一年又是在原地踏步！”

    “哎，这废物真是把家族的脸都给丢光了。”

    “要不是族长是他的父亲，这种废物，早就被驱赶出家族，任其自生自灭了，哪还有机会待在家族中白吃白喝。”

    “唉，昔年那名闻乌坦城的天才少年，如今怎么落魄成这般模样了啊？”

    “谁知道呢，或许做了什么亏心事，惹得神灵降怒了吧…”

    周围传来的不屑嘲笑以及惋惜轻叹，落在那如木桩待在原地的少年耳中，恍如一根根利刺狠狠的扎在心脏一般，让得少年呼吸微微急促。
    ..."]

**Comment by Morizeyao** [comment]
...别手填，做成list用json库导出。
兄弟我看你问题好像挺多的，要不考虑一下加交流群交流？里面群友都很热心

**Comment by jason5675** [comment]
我一直想进啊  你也不拉我   怎么进？

**Comment by Morizeyao** [comment]
微信密我下

**Comment by jason5675** [comment]
i16181618   微信号。

**Comment by lioyou** [comment]
@jason5675 
数据的格式不一定要json，什么数据都可以，最终都要转成index，当然为了使用这个库，需要将所有数据变成一个列表list[line1,line2,line3,...]
```python
# 这个是train.py中的处理数据的方法，可以直接在这里改
def build_files(data_path, tokenized_data_path, num_pieces, full_tokenizer, min_length):
    with open(data_path, 'r', encoding='utf8') as f:
        print('reading lines')
        lines = json.load(f)
        lines = [line.replace('\n', ' [SEP] ') for line in lines]  # 用[SEP]表示换行, 段落之间使用SEP表示段落结束
    all_len = len(lines)
```
可以改成这个样子，其它的不变，【SEP】要不要，你要知道这个的作用，在此添加，我想起不到其换行作用的，在分词时，【SEP】会被分割的，最终查找词典时，就不是单个【SEP】了，而是多个组成，所以bug。
```python
# 如果文件格式是txt
def build_files(data_path, tokenized_data_path, num_pieces, full_tokenizer, min_length):
    with open(data_path,'r',encoding='utf8') as f:
        content = f.read()
        # 使用正则分割所有章节
        lines = []
        lines.append(#每一章的内容)
    all_len = len(lines)
```
**所有的模型都接收index列表作为输入，所以无论你的数据源是DB，txt，json，还是其它，最终都要分词，查表变成索引列表作为输入，花点时间好好读一次代码，自然就懂了。**
